version: "3.3"

services:

  nginx:
    image: nginx
    ports:
      - 443:443
    volumes:
      - ./conf/reg.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs    
    depends_on:
      - reg

  reg:
    image: registry:2
    expose:
        - 5000
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/example.crt
      REGISTRY_HTTP_TLS_KEY: /certs/example.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_HTTP_SECRET: ${REGISTRY_HTTP_SECRET}
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000 # Sorta... Not really 0.0.0.0, 5000 Not Exposed to Host
      REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR: redis
      REGISTRY_REDIS_ADDR: redis:6379
    volumes:
      - ./data:/var/lib/registry # For Persisting Layers to Disk, Not Redis!
      - ./certs:/certs
      - ./auth:/auth

  redis: 
    image: library/redis
    expose:
      - 6379
    command: redis-server /redis.conf
    volumes:
      - ./redis/redis.conf:/redis.conf
