version: "3.3"

services:

  reg:
    image: registry:2
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/example.crt
      REGISTRY_HTTP_TLS_KEY: /certs/example.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_HTTP_SECRET: '${REGISTRY_HTTP_SECRET}'
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - ./data:/var/lib/registry
      - ./certs:/certs
      - ./auth:/auth

  nginx:

    image: nginx
    ports:
      - 443:443
    volumes:
      - ./conf/reg.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    
    depends_on:
      - reg

      